# This file is adapted from `maturin generate-ci github`
name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
